/**
 * midnight-client.ts
 *
 * Real Midnight SDK client for browser dApp use.
 *
 * Uses the official DApp Connector API (CAIP-372):
 *   window.midnight.<wallet>.connect(networkId) → ConnectedAPI
 *
 * Key reviewer requirements addressed:
 *   - setNetworkId() called before any SDK operation (fix #10)
 *   - wallet.connect(networkId) used as per DApp Connector API (fix #3)
 *   - Real increment circuit via findDeployedContract + callTx (fix #5)
 *   - Transaction submitted through connected wallet (fix #6)
 *   - Counter read from Midnight Preprod indexer (fix #7)
 *   - No setTimeout() simulation, no Math.random() hashes (fix #8)
 */

import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';

// Compiled contract artifacts — generated by `compact compile counter.compact`
import { Contract, ledger } from '../../../contracts/counter/artifacts/contract/index.js';

// ---------------------------------------------------------------------------
// Network configuration — Midnight Preprod
// ---------------------------------------------------------------------------

export const NETWORK_ID = 'preprod';

export const PREPROD_CONFIG = {
  indexer: 'https://indexer.preprod.midnight.network/api/v1/graphql',
  indexerWS: 'wss://indexer.preprod.midnight.network/api/v1/graphql/ws',
  proofServer: 'https://proof-server.preprod.midnight.network',
};

export const CONTRACT_ADDRESS =
  '749e975e165abd69dd52f97c31202ad73175993ab046a3b6bb420b3e81d61a7d';

const PRIVATE_STATE_ID = 'counterPrivateState';

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

export interface IncrementResult {
  txHash: string;
  newValue: bigint;
}

// ---------------------------------------------------------------------------
// Browser ZK config provider
// Loads prover/verifier keys and ZKIR from the committed artifacts directory.
// ---------------------------------------------------------------------------

function makeBrowserZkConfigProvider() {
  return {
    getProverKey: async (circuitId: string): Promise<Uint8Array> => {
      const res = await fetch(`/artifacts/keys/${circuitId}.prover`);
      if (!res.ok) throw new Error(`Failed to load prover key for ${circuitId}`);
      return new Uint8Array(await res.arrayBuffer());
    },
    getVerifierKey: async (circuitId: string): Promise<Uint8Array> => {
      const res = await fetch(`/artifacts/keys/${circuitId}.verifier`);
      if (!res.ok) throw new Error(`Failed to load verifier key for ${circuitId}`);
      return new Uint8Array(await res.arrayBuffer());
    },
    getZkir: async (circuitId: string): Promise<Uint8Array> => {
      const res = await fetch(`/artifacts/zkir/${circuitId}.bzkir`);
      if (!res.ok) throw new Error(`Failed to load ZKIR for ${circuitId}`);
      return new Uint8Array(await res.arrayBuffer());
    },
  };
}

// ---------------------------------------------------------------------------
// getCounterState — read counter from Midnight Preprod indexer
// ---------------------------------------------------------------------------

export async function getCounterState(): Promise<bigint> {
  // setNetworkId must be called before any SDK operation
  setNetworkId(NETWORK_ID);

  const publicDataProvider = indexerPublicDataProvider(
    PREPROD_CONFIG.indexer,
    PREPROD_CONFIG.indexerWS,
  );

  const contractState = await publicDataProvider.queryContractState(CONTRACT_ADDRESS);
  if (!contractState) return 0n;

  return ledger(contractState.data).counter;
}

// ---------------------------------------------------------------------------
// increment — execute the real increment circuit through Midnight.js
// ---------------------------------------------------------------------------

export async function increment(
  witnessValue: bigint,
  walletApi: unknown,
): Promise<IncrementResult> {
  if (witnessValue <= 0n) {
    throw new Error('Witness must be a positive integer.');
  }

  // Step 1 — set global network ID (fix #10)
  setNetworkId(NETWORK_ID);

  // Step 2 — build providers
  const publicDataProvider = indexerPublicDataProvider(
    PREPROD_CONFIG.indexer,
    PREPROD_CONFIG.indexerWS,
  );
  const zkConfigProvider = makeBrowserZkConfigProvider();
  const proofProvider = httpClientProofProvider(
    PREPROD_CONFIG.proofServer,
    zkConfigProvider as never,
  );

  // Step 3 — build the compiled contract with the private witness function
  // The witness function keeps witnessValue private — it is never sent on-chain
  const compiledContract = {
    contract: Contract,
    witnesses: {
      incrementWitness: () => [{}, witnessValue] as [Record<string, never>, bigint],
    },
  };

  const providers = {
    publicDataProvider,
    proofProvider,
    // walletApi is the ConnectedAPI from wallet.connect(networkId) (fix #3, #6)
    walletProvider: walletApi as never,
    midnightProvider: walletApi as never,
    // Counter contract has no private state fields
    privateStateProvider: {
      get: async () => ({}),
      set: async () => {},
      remove: async () => {},
    } as never,
    zkConfigProvider: zkConfigProvider as never,
  };

  // Step 4 — find the already-deployed contract on Preprod (fix #4)
  const deployed = await findDeployedContract(providers as never, {
    compiledContract: compiledContract as never,
    contractAddress: CONTRACT_ADDRESS,
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState: {},
  } as never);

  // Step 5 — call the real increment circuit (fix #5)
  // This generates the ZK proof locally and submits the tx through the wallet (fix #6)
  const txData = await (deployed as unknown as {
    callTx: {
      increment: () => Promise<{ public: { txId: string } }>;
    };
  }).callTx.increment();

  const txHash = txData.public.txId;

  // Step 6 — read updated state from Preprod indexer (fix #7)
  const updatedState = await publicDataProvider.queryContractState(CONTRACT_ADDRESS);
  const newValue = updatedState ? ledger(updatedState.data).counter : 0n;

  return { txHash, newValue };
}
